jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn eslint
          name: Run ESLint
  
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: bundle exec fastlane android release
          name: Run Fastlane
orbs:
  rn: react-native-community/react-native@7.0.0
  jira: circleci/jira@1.3.0

version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
          post-steps:
            - jira/notify:
                environment: hdhhdhhdh
                environment_type: staging
                job_type: build
                scan_commit_body: true
#       - rn/android_build:
#           build_type: release
#           requires:
#             - analyse_js
#       - rn/android_test:
#           requires:
#             - rn/android_build
#           post-steps:
#             - jira/notify:
#                 environment_type: staging
#                 job_type: build
#                 scan_commit_body: true
#       - fastlane_release:
#           requires:
#             - rn/android_test
