jobs:
  pre-build: &pre-build
    executor: rn/linux_js
    environment:
      CURRENT_BUILD: 0
      CIRCLE_BUILD_NUM_ADJUST: 99
    steps:
      - run:
          name: Writing Build Number to a text file
          command: echo "BuildNumber_"$(( $CIRCLE_BUILD_NUM + $CIRCLE_BUILD_NUM_ADJUST ))"_" > buildnumber.txt
      - run: cat buildnumber.txt
      - persist_to_workspace:
          root: .
          paths:
            - buildnumber.txt
            - ./builddetails/
          
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run: echo $CIRCLE_BUILD_NUM
      - run: cat buildnumber.txt
      - run: echo $(cat ../buildnumber.txt | awk -F_ '{print $2}')
#       - run: echo 'export CIRCLE_BUILD_NUM="1234"' >> $BASH_ENV
#       - run: echo $CIRCLE_BUILD_NUM
  
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: bundle exec fastlane android release
          name: Run Fastlane
orbs:
  rn: react-native-community/react-native@7.0.0
  jira: circleci/jira@1.3.0

version: 2.1
workflows:
  test:
    jobs:
      - pre-build
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
          post-steps:
            - jira/notify:
                environment: "hdhhdhhdh"
                environment_type: staging
                job_type: deployment
                scan_commit_body: true
#       - rn/android_build:
#           build_type: release
#           requires:
#             - analyse_js
#       - rn/android_test:
#           requires:
#             - rn/android_build
#           post-steps:
#             - jira/notify:
#                 environment_type: staging
#                 job_type: build
#                 scan_commit_body: true
#       - fastlane_release:
#           requires:
#             - rn/android_test

